version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    working_dir: /usr/src/test-task
    restart: always

    volumes:
      - ./:/usr/src/test-task
    ports:
      - 4000:4000
